DROP TABLE IF EXISTS version;
CREATE TABLE IF NOT EXISTS version (version VARCHAR(16));

INSERT INTO version VALUES (0);

CREATE TABLE IF NOT EXISTS ts (id SERIAL, time TIMESTAMPTZ, sensor VARCHAR(256), value REAL);
